target-version = "py312"
exclude = ["__init__.py"] # Waiting for non preview fixes for F401 & F403

[lint]
select = [
    # pycodestyle
    "E", "W",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # comprehensions
    "C4",
    # prints
    "T20",
]
ignore = ["E501"] # Line-too-long
