from modules.utils.foxhole_types import StockpileTypes

REGIONS = {
    'Acrithia': ['Patridia', 'Nereid Kepp', 'The Brimehold', 'Legion Ranch', 'Camp Omicron', 'Heir Apparent', 'Thetus Ring', 'Swordfort'],
    "Allod's Bight": ['The Stone Plank', "Mercy's Wail", 'The Turncoat', 'Belaying Trace', 'Homesick', 'Rumhold', 'Scurvyshire'],
    'Ash Fields': ['Cometa', 'The Calamity', 'Ashtown', 'Sootflow', 'The Ashfort', 'Camp Omega', 'Electi'],
    'Basin Sionnach': ['Cuttail Station', 'Stoic', 'Lamplight', 'The Den', 'Bassinhome', 'Sess'],
    "Callahan's Passage": ['Cragstown', 'White Chapel', 'The Procession', 'The Latch', 'Overlook Hill', 'Crumbling Passage', 'Crumbling Post', 'Scáth Passing', 'Lochan Berth', 'Solas Gorge'],
    "Callum's Cape": ['Naofa', 'Scouts Jest', 'Ire', 'Lookout', 'Holdout', 'Camp Hollow', "Callum's Keep"],
    'Clanshead Valley': ['Fallen Crown', 'Fort Windham', 'The King', 'Sweetholt', 'Fort Esterwild', 'The Pike', 'Fort Ealar'],
    'Deadlands': ['The Salt Farms', 'Brine Glen', 'The Salt March', "Callahan's Gate", "Callahan's Boot", "Iron's End", 'The Spine', 'Liberation Point', "Sun's Hollow", 'The Pits', 'Abandoned Ward'],
    'Endless Shore': ['Iron Junction', 'The Overland', 'Woodbind', 'Tuatha Watchpost', 'Evil Eye', 'Dannan Ridge', 'Vulpine Watch', 'Wellchurch', 'Brackish Point', 'Saltbrook Channel', 'Enduring Wake', 'The Old Jack Tar'],
    'Farranac Coast': ['Victa', 'Pleading Wharf', "Macha's Keening", 'Mara', 'Scythe', 'The Jade Cove', 'Scarp of Ambrose', 'Luxta Homestead', 'The Bone Haft', 'The Spearhead', 'Terra'],
    "Fisherman's Row": ['Arcadia', 'Fort Ember', 'The Satyr Stone', "Hangmen's Court", 'The Tree Sisters', 'Eidolo', 'Peripti Landing', 'Black Well', 'Oceanwatch', 'Partisan Island'],
    'Godcrofts': ['Anchor Beach', 'Blackwatch', 'Protos', 'The Axehead', 'Skodio', 'Promithiens', 'Isawa', 'The Fleece Road'],
    'Great March': ['Violethome', 'Leto', 'Camo Senti', "Myrmidon's Stay", 'Remnant Villa', 'Lionsfort', 'Dendro Field', "Sitaria", 'The Swan'],
    'Howl County': ['Hungry Wolf', 'Slipgate Outpost', 'Great Warden Dam', 'Fort Red', 'Sickelshire', 'Little Lamb', 'Teller Farm', 'Fort Rider'],
    'Kalokai': ["Night's Regret", 'Sourtooth', 'Sweetearth', 'Camp Tau', 'Hallow', 'Baccae Ridge', 'Lost Greensward'],
    'Loch Mór': ['Market Road', 'Tomb of the First', "Mercy's Wish", 'Westmarch', "Moon's Copse", 'The Roilfort', 'Feirmor'],
    'Marban Hollow': ['Lockheed', 'Oster Wall', 'Mox', 'Checkpoint Bua', "Maiden's Veil", 'The Spitrocks', 'Sanctum'],
    "Morgen's Crossing": ['Eversus', 'Allsight', "Bastard's Block", 'Quietus', 'Lividus', 'Warmonger Bay'],
    'Nevish Line': ['Blinding Stones', 'The Scrying Belt', 'Unruly', 'Mistle Shrine', 'Grief Mother', 'Princefal', 'Blackcoat Way', 'Tomb Father'],
    'Origin': ['Finis', 'Arise', 'Initium', 'Dormio', 'World Star', 'Teichotima'],
    'Reaching Trail': ['Limestone Holdfast', 'Dwyerstown', 'Brodytown', 'Elksford', 'Ice Ranch', 'Nightchurch', 'Harpy', 'Reprieve', "Fort Mac Conaill's", 'The Ark', 'Mousetrap'],
    'Red River': ['Camp Upsilon', 'Penance', 'Fort Matchwood', 'Climb', 'Judicium', 'Victoria Hill', 'Cannonsmoke', 'Minos'],
    'Schackeld Chasm': ['Savages', 'The Grave of Erastos', 'The Beli Toll', 'Firstmarch', 'The Vanguard', 'Limewood Holdfast', 'Gorgon Grove', 'Reflection', 'Silk Farm', "Simo's Run"],
    'Speaking Woods': ['Hush', 'Inari Base', 'Tine', 'Sotto Bank', 'Fort Blather', 'Stem', 'The Filament', 'Wound'],
    'Stonecradle': ['The Dais', 'The Reach', 'Trammel Pool', 'Fading Lights', 'The Cord', 'Buckler Sound', "World's End", "The Heir's Knife", 'The Long Fast'],
    'Tempest Island': ['Isle of Psyche', 'The Gale', "Liar's Heaven", 'The Iris', 'Surge Gate', 'The Rush', 'Reef', 'Lost Airchal', 'Alchimio Estate'],
    'Terminus': ['Therizó', 'Bloody Palm', 'Winding Bolas', 'Thunderbolt', "Warlord's Stead", 'Cerberus Wake'],
    'The Drowned Vale': ['Loggerhead', "Wisp's Warning", 'The Wash', 'Eastmarch', 'Vessel', 'Splinter Pens', 'The Baths', 'Coaldrifter Stead', 'Bootnap', 'Singing Serpents', 'The Saltcaps'],
    'The Fingers': ['Titancall', 'The Old Captain', 'Fort Barley', 'Second Man', 'The Routed', 'The Tusk', "Headsman's Villa", 'Plankhouse'],
    'The Heartlands': ['Deeplaw Post', 'The Breach', 'Barrony Ranch', 'The Plough', 'Greenfield Orchard', 'Fort Providence', 'The Blemish', 'Barronswall', 'Oleander Homestead', 'Proexí'],
    'The Linn of Mercy': ['The Long Whine', 'Rotdust', 'Lathair', 'Outwich Ranch', 'Fort Duncan', 'The Prairie Bazaar', 'The First Coin', 'The Last Grove', 'The Crimson Gardens', 'Hardline', 'Ulster Falls'],
    'The Moors': ['Reaching River', 'The Spade', 'Headstone', "Gravekeeper's Holdfast", 'The Cut', 'The Wind Hills', 'MacConmara Barrows', 'Wiccwalk', "Morrighan's Grave", "Luch's Workshop", 'Borderlane', 'Reaching River', 'Ogmaran'],
    'The Oarbreaker Isles': ['Gold', 'Reliqua', 'The Ides', 'Posterus', 'Skelter Course', 'The Conclave', "Lion's Head", 'Integrum', 'Base Akri'],
    'Umbral Wildwood': ['The Foundry', 'Golden Root Ranch', 'Thunderfoot', 'Sentry', "Atropos' Fate", "Hermit's Rest", "Lachesis' Tally", 'Amethyst', "Clotho's Refuge", 'Vagrant Bastion', 'Stray'],
    'Viper Pit': ["Serenity's Blight", 'Flech Crossing', 'Earl Crowley', 'Molworth', 'Blackthroat', 'The Friars', 'Fort Viêr', 'Fleck Crossing', 'Kirknell'],
    'Weathered Expanse': ['The Weathering Halls', 'Port of Rime', 'Wightwalk', 'Huntsfort', 'Shattered Advance', 'Frostmarch', "Crow's Nest", 'Necropolis', 'Foxcatcher'],
    'Westgate': ['Sanctuary', 'The Gallows', 'Holdfast', "Rancher's Fast", 'Kingstown', "Lord's Mouth", 'Lost Partition', 'Westgate Keep', 'Longstone', "Zeus' Demise", 'Wyattwick']
}

REGIONS_STOCKPILES = {
    'Acrithia': [('Legion Ranch', StockpileTypes.STORAGE_DEPOT.value), ('Patridia', StockpileTypes.SEAPORT.value), ('Thetus Ring', StockpileTypes.STORAGE_DEPOT.value)],
    "Allod's Bight": [("Mercy's Wail", StockpileTypes.SEAPORT.value), ('Scurvyshire', StockpileTypes.STORAGE_DEPOT.value)],
    'Ash Fields': [('Ashtown', StockpileTypes.SEAPORT.value), ('Electi', StockpileTypes.STORAGE_DEPOT.value)],
    'Basin Sionnach': [('Cuttail Station', StockpileTypes.SEAPORT.value), ('Sess', StockpileTypes.STORAGE_DEPOT.value), ('The Den', StockpileTypes.STORAGE_DEPOT.value)],
    "Callahan's Passage": [('Lochan Berth', StockpileTypes.SEAPORT.value), ('Solas Gorge', StockpileTypes.STORAGE_DEPOT.value)],
    "Callum's Cape": [("Callum's Keep", StockpileTypes.SEAPORT.value), ('Holdout', StockpileTypes.STORAGE_DEPOT.value)],
    'Clanshead Valley': [('The King', StockpileTypes.SEAPORT.value), ('The Pike', StockpileTypes.STORAGE_DEPOT.value)],
    'Deadlands': [('Abandoned Ward', StockpileTypes.STORAGE_DEPOT.value), ('Brine Glen', StockpileTypes.STORAGE_DEPOT.value), ("Callahan's Gate", StockpileTypes.STORAGE_DEPOT.value), ('The Salt Farms', StockpileTypes.STORAGE_DEPOT.value), ('The Spine', StockpileTypes.STORAGE_DEPOT.value)],
    'Endless Shore': [('Brackish Point', StockpileTypes.STORAGE_DEPOT.value), ('Iron Junction', StockpileTypes.STORAGE_DEPOT.value), ('Saltbrook Channel', StockpileTypes.SEAPORT.value)],
    'Farranac Coast': [('Mara', StockpileTypes.STORAGE_DEPOT.value), ('The Jade Cove', StockpileTypes.SEAPORT.value), ('Victa', StockpileTypes.STORAGE_DEPOT.value)],
    "Fisherman's Row": [('Black Well', StockpileTypes.STORAGE_DEPOT.value), ('Eidolo', StockpileTypes.SEAPORT.value), ("Hangmen's Court", StockpileTypes.STORAGE_DEPOT.value), ('Partisan Island', StockpileTypes.STORAGE_DEPOT.value)],
    'Godcrofts': [('Blackwatch', StockpileTypes.STORAGE_DEPOT.value), ('Skodio', StockpileTypes.STORAGE_DEPOT.value), ('The Axehead', StockpileTypes.SEAPORT.value)],
    'Great March': [("Myrmidon's Stay", StockpileTypes.STORAGE_DEPOT.value), ('Sitaria', StockpileTypes.STORAGE_DEPOT.value), ('Violethome', StockpileTypes.STORAGE_DEPOT.value)],
    'Howl County': [('Great Warden Dam', StockpileTypes.SEAPORT.value), ('Hungry Wolf', StockpileTypes.STORAGE_DEPOT.value), ('Little Lamb', StockpileTypes.STORAGE_DEPOT.value)],
    'Kalokai': [('Baccae Ridge', StockpileTypes.SEAPORT.value), ('Hallow', StockpileTypes.STORAGE_DEPOT.value), ('Sweetearth', StockpileTypes.STORAGE_DEPOT.value)],
    "King's Cage": [('Gibbet Fields', StockpileTypes.STORAGE_DEPOT.value), ('The Manacle', StockpileTypes.SEAPORT.value)],
    'Loch Mór': [('Feirmor', StockpileTypes.SEAPORT.value), ("Mercy's Wish", StockpileTypes.STORAGE_DEPOT.value)],
    'Marban Hollow': [('Lockheed', StockpileTypes.STORAGE_DEPOT.value), ("Maiden's Veil", StockpileTypes.SEAPORT.value)],
    "Morgen's Crossing": [('Allsight', StockpileTypes.STORAGE_DEPOT.value), ('Lividus', StockpileTypes.STORAGE_DEPOT.value), ('Quietus', StockpileTypes.SEAPORT.value)],
    'Nevish Line': [('Blackcoat Way', StockpileTypes.STORAGE_DEPOT.value), ('Mistle Shrine', StockpileTypes.STORAGE_DEPOT.value), ('The Scrying Belt', StockpileTypes.SEAPORT.value)],
    'Origin': [('Finis', StockpileTypes.STORAGE_DEPOT.value), ('Initium', StockpileTypes.SEAPORT.value), ('Teichotima', StockpileTypes.STORAGE_DEPOT.value)],
    'Reaching Trail': [('Brodytown', StockpileTypes.STORAGE_DEPOT.value), ('Nightchurch', StockpileTypes.STORAGE_DEPOT.value), ('Reprieve', StockpileTypes.STORAGE_DEPOT.value)],
    'Red River': [('Cannonsmoke', StockpileTypes.SEAPORT.value), ('Judicium', StockpileTypes.STORAGE_DEPOT.value), ('Penance', StockpileTypes.STORAGE_DEPOT.value)],
    'Sableport': [('Barronhome', StockpileTypes.STORAGE_DEPOT.value), ('Cinderwick', StockpileTypes.STORAGE_DEPOT.value), ("Light's End", StockpileTypes.SEAPORT.value)],
    'Schackeld Chasm': [('Savages', StockpileTypes.STORAGE_DEPOT.value), ('Silk Farm', StockpileTypes.SEAPORT.value), ('The Grave of Erastos', StockpileTypes.STORAGE_DEPOT.value)],
    'Speaking Woods': [('Sotto Bank', StockpileTypes.STORAGE_DEPOT.value), ('The Filament', StockpileTypes.STORAGE_DEPOT.value), ('Tine', StockpileTypes.SEAPORT.value)],
    'Stonecradle': [('Buckler Sound', StockpileTypes.SEAPORT.value), ('Fading Lights', StockpileTypes.STORAGE_DEPOT.value)],
    'Tempest Island': [('Alchimio Estate', StockpileTypes.STORAGE_DEPOT.value), ('Isle of Psyche', StockpileTypes.STORAGE_DEPOT.value), ("Liar's Heaven", StockpileTypes.SEAPORT.value)],
    'Terminus': [('Therizó', StockpileTypes.STORAGE_DEPOT.value), ("Warlord's Stead", StockpileTypes.SEAPORT.value)],
    'The Drowned Vale': [('Loggerhead', StockpileTypes.STORAGE_DEPOT.value), ('The Baths', StockpileTypes.SEAPORT.value)],
    'The Fingers': [("Headsman's Villa", StockpileTypes.STORAGE_DEPOT.value), ('The Old Captain', StockpileTypes.SEAPORT.value), ('The Routed', StockpileTypes.STORAGE_DEPOT.value)],
    'The Heartlands': [('Greenfield Orchard', StockpileTypes.STORAGE_DEPOT.value), ('The Blemish', StockpileTypes.STORAGE_DEPOT.value)],
    'The Linn of Mercy': [('The Prairie Bazaar', StockpileTypes.STORAGE_DEPOT.value), ('Ulster Falls', StockpileTypes.SEAPORT.value)],
    'The Moors': [("Morrighan's Grave", StockpileTypes.STORAGE_DEPOT.value), ('Ogmaran', StockpileTypes.SEAPORT.value)],
    'The Oarbreaker Isles': [('Integrum', StockpileTypes.STORAGE_DEPOT.value), ('Skelter Course', StockpileTypes.SEAPORT.value), ('The Ides', StockpileTypes.STORAGE_DEPOT.value)],
    'Umbral Wildwood': [("Hermit's Rest", StockpileTypes.STORAGE_DEPOT.value), ('Thunderfoot', StockpileTypes.SEAPORT.value)],
    'Viper Pit': [('Earl Crowley', StockpileTypes.STORAGE_DEPOT.value), ('Kirknell', StockpileTypes.SEAPORT.value)],
    'Weathered Expanse': [("Crow's Nest", StockpileTypes.STORAGE_DEPOT.value), ('Foxcatcher', StockpileTypes.STORAGE_DEPOT.value), ('Port of Rime', StockpileTypes.SEAPORT.value)],
    'Westgate': [('Kingstown', StockpileTypes.STORAGE_DEPOT.value), ('Longstone', StockpileTypes.SEAPORT.value), ('The Gallows', StockpileTypes.STORAGE_DEPOT.value)]
}

REGIONS_NAMES_API = [
    'HomeRegionC',
    'HomeRegionW',
    'AcrithiaHex',
    'AllodsBightHex',
    'AshFieldsHex',
    'BasinSionnachHex',
    'CallahansPassageHex',
    'CallumsCapeHex',
    'ClansheadValleyHex',
    'DeadlandsHex',
    'DrownedValeHex',
    'EndlessShoreHex',
    'FarranacCoastHex',
    'FishermansRowHex',
    'GodcroftsHex',
    'GreatMarchHex',
    'HeartlandsHex',
    'HowlCountyHex',
    'KalokaiHex',
    'KingsCageHex',
    'LinnMercyHex',
    'LochMorHex',
    'MarbanHollow',
    'MooringCountyHex',
    'MorgensCrossingHex',
    'NevishLineHex',
    'OarbreakerHex',
    'OriginHex',
    'ReachingTrailHex',
    'RedRiverHex',
    'SableportHex',
    'ShackledChasmHex',
    'SpeakingWoodsHex',
    'StonecradleHex',
    'TempestIslandHex',
    'TerminusHex',
    'TheFingersHex',
    'UmbralWildwoodHex',
    'ViperPitHex',
    'WeatheredExpanseHex',
    'WestgateHex'
]
