import pathlib

from . import WorldSpawnTypes

OISOL_HOME_PATH = pathlib.Path('/') / 'oisol'

TODOLIST_MAXIMUM_TASKS_ON_INTERFACE = 24


NUMBER_TO_EQUIPMENT_SLOT = {
    '1': 'Primary Equipment',
    '2': 'Secondary Equipment',
    '3': 'Tertiary Equipment',
    '4': 'Attachment',
    '5': 'Headgear',
    '6': 'Uniform',
    '7': 'Extra Equipment',
    '8': 'Large Item',
}


EMOJIS_FROM_DICT = {
    'Small Arms': 'small_arms',
    'Heavy Arms': 'heavy_arms',
    'Heavy Ammunition': 'heavy_ammunition',
    'Utility': 'utility',
    'Medical': 'medical',
    'Resource': 'resource',
    'Light Kinetic': 'light_kinetic',
    'Heavy Kinetic': 'heavy_kinetic',
    'Anti-Tank Kinetic': 'at_kinetic',
    'Anti-Tank Explosive': 'at_explosive',
    'Anti-Tank Pillbox': 'at_pillbox',
    'Explosive': 'explosive',
    'Flare': 'flare',
    'Melee': 'fists',
    'High Explosive': 'high_explosive',
    'Armour Piercing': 'armour_piercing',
    'Fire': 'fire',
    'Poisonous Gas': 'poisonous_gas',
    'Demolition': 'demolition',
    'Shrapnel': 'shrapnel',
    'Incendiary High Explosive': 'incendiary_high_explosive',
    'Incendiary': 'incendiary',
    'Flamethrower Ammo': 'flamethrower_ammo',
    'Flame Ammo': 'flame_ammo',
    '“Molten Wind” v.II Ammo': 'molten_wind_ammo',
    'Shrapnel Mortar Shell': 'shrapnel_mortar_shell',
    'Incendiary Mortar Shell': 'incendiary_mortar_shell',
    'Tracks': 'tracked',
    'Fuel Tank': 'fuel_leak',
    'Turret': 'turreted',
    'Second Turret/Cannon': 'turreted',
    'Naval Hull Segments': 'naval_hull_segments',
    'Naval Shell Plating': 'naval_shell_plating',
    'Naval Turbine Components': 'naval_turbine_components',
    'Assembly Materials I': 'amat1',
    'Assembly Materials II': 'amat2',
    'Assembly Materials III': 'amat3',
    'Assembly Materials IV': 'amat4',
    'Assembly Materials V': 'amat5',
    'Crate': 'crate',
    'Refined Materials': 'rmat',
    'Basic Materials': 'bmat',
    'Explosive Powder': 'emat',
    'Heavy Explosive Powder': 'hemat',
    'Construction Materials': 'cmat',
    'Processed Construction Materials': 'pcmat',
    'Steel Construction Materials': 'scmat',
    'Rare Alloys': 'rare_alloy',
    'Unstable Substances': 'unstable_substances',
    'Thermal Shielding': 'thermal_shielding',
    'LegendLargeShips': 'large_ship_intel',
    'LegendFacilities': 'facility_intel',
    'LegendMedical': 'medical_intel',
    'LegendStructure': 'tower_intel',
    'LegendArtillery': 'arty_intel',
    'LegendDefense': 'defense_intel',
    'LegendOutpost': 'outpost_intel',
    'Shovel': 'shovel',
    'Hammer': 'hammer',
    'Construction Vehicle': 'construction_vehicle',
    'Concrete Materials': 'concrete',
    'Diesel': 'diesel',
    'Petrol': 'petrol',
    'Heavy Oil': 'hoil',
    'Enriched Oil': 'eoil',
    'Buckshot': 'buckshot',
    '.44': '_44',
    '7.62mm': '7_62mm',
    '7.92mm': '7_92mm',
    '8mm': '8mm',
    '9mm': '9mm',
    '12.7mm': '12_7mm',
    '20mm': '20mm',
    '30mm': '30mm',
    '40mm': '40mm',
    '68mm': '68mm',
    '75mm': '75mm',
    '94.5mm': '94_5mm',
    '120mm': '120mm',
    '150mm': '150mm',
    '300mm': '300mm',
    'Torpedo': 'torpedo',
    'Moray Torpedo': 'torpedo',
    'Depth Charge': 'depth_charge',
    'Model-7 “Evie”': 'depth_charge',
    'RPG': 'rpg',
    'ARC⧸RPG': 'arc_rpg',
    '250mm': '250mm_purity',
    '250mm “Purity” Shell': '250mm_purity',
    '250mm “Fury” Shell': '250mm_fury',
    '3C-High Explosive Rocket': '3c_rocket',
    '4C-Fire Rocket': '4c_rocket',
    'Havoc Charge': 'havoc',
    'Mortar Shell': 'mortar_shell',
    'Alligator Charge': 'satchel',
    "Hydra's Whisper": 'hydras',
    'Hydra&#039;s Whisper': 'hydras',
    'Shatter Missile': 'shatter_missile',
    'Mammon 91-b': 'mammon',
    'Ignifist 30': 'ignifist',
    'AP⧸RPG': 'ap_rpg',
    'BF5 White Ash Flask Grenade': 'flask',
    'Anti-Tank Sticky Bomb': 'sticky',
    'B2 Varsi Anti-Tank Grenade': 'varsi',
    'Abisme AT-99': 'at_mine',
    "Crow's Foot Mine": 'infantry_mine',
    'Crow&#039;s Foot Mine': 'infantry_mine',
    'MapIconTownBase1': 'townbase_t1',
    'MapIconTownBase2': 'townbase_t2',
    'MapIconTownBase3': 'townbase_t3',
    'MapIconBunkerBaseT1': 'bunkerbase_t1',
    'MapIconBunkerBaseT2': 'bunkerbase_t2',
    'MapIconBunkerBaseT3': 'bunkerbase_t3',
    'MapIconBorderBase': 'borderbase',
    'MapIcon Encampment': 'encampment',
    'Map Icon Keep': 'keep',
    'MapIconLiquidTransferStation': 'lts',
    'MapIconMaterialTransferStation': 'mts',
    'MapIconResourceTransferStation': 'rts',
    'MapIconShipyard': 'shipyard',
    'MapIconConstructionYard': 'construction_yard',
    'Tech Center Map Icon': 'tech_center',
    'Mass Production Factory': 'mpf',
    'Factory': 'factory',
    'Garage': 'garage',
    'MW of power': 'power',
    'Small Assembly Station': 'small_assembly_station',
    'Infantry Arms Factory': 'infantry_facility',
    'MapIconManufacturing': 'refinery',
    'MapIconSeaport': 'seaport',
    'MapIconStorageFacility': 'storage_depot',
    'MapIconComponentMine': 'component_mine',
    'MapIconComponents': 'component_field',
    'MapIconSulfur': 'sulfur_field',
    'MapIconSulfurMine': 'sulfur_mine',
    'MapIconScrap': 'salvage_field',
    'MapIconScrapMine': 'salvage_mine',
    'MapIconFuel': 'oil_field',
    'MapIconCoal': 'coal_field',
    'MapIconRocketSite': 'rocket_site',
    'A3 Harpa Fragmentation Grenade': 'harpa',
    'Bomastone Grenade': 'bomastone',
    'Tremola Grenade GPb-1': 'tremola',
    'PT-815 Smoke Grenade': 'smoke',
    'Green Ash Grenade': 'gas_grenade',
    'Sea Mine': 'sea_mine',
    'E680-S Rudder Lock': 'sea_mine',
    'A0E-9 Rocket Warhead': 'rocket_warhead',
    'A0E-9 Rocket Body': 'rocket_body',
    'A0E-9 Rocket Booster': 'rocket_booster',
	'Salvage': 'salvage',
	'Coke': 'coke',
	'Sulfur': 'sulfur',
	'Mark II Raidbreaker': 'mark_ii_raidbreaker',
	'E681-B Hullbreaker Mine': 'hullbreaker_navalmine',
	'912 Shrike Rounds': 'dive_bomber_ammo',
	'14.5mm': '14_5mm',
	'950-70b Anti-Aircraft Shell': 'anti_aircraft_shell',
}


EMOTES_CUSTOM_ID = {
    '🇦': 'TodoButtonA',
    '🇧': 'TodoButtonB',
    '🇨': 'TodoButtonC',
    '🇩': 'TodoButtonD',
    '🇪': 'TodoButtonE',
    '🇫': 'TodoButtonF',
    '🇬': 'TodoButtonG',
    '🇭': 'TodoButtonH',
    '🇮': 'TodoButtonI',
    '🇯': 'TodoButtonJ',
    '🇰': 'TodoButtonK',
    '🇱': 'TodoButtonL',
    '🇲': 'TodoButtonM',
    '🇳': 'TodoButtonN',
    '🇴': 'TodoButtonO',
    '🇵': 'TodoButtonP',
    '🇶': 'TodoButtonQ',
    '🇷': 'TodoButtonR',
    '🇸': 'TodoButtonS',
    '🇹': 'TodoButtonT',
    '🇺': 'TodoButtonU',
    '🇻': 'TodoButtonV',
    '🇼': 'TodoButtonW',
    '🇽': 'TodoButtonX',
    '🇾': 'TodoButtonY',
    '🇿': 'TodoButtonZ',
}


REGIONS_TYPES = {
    # The Fingers
    "Headsman's Villa": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
    'The Old Captain': WorldSpawnTypes.TOWN_BASE_SCHOOL,
    'Plankhouse': WorldSpawnTypes.RELIC_SMALL,
    'Second Man': WorldSpawnTypes.RELIC_MEDIUM,
    'Tethys Base': WorldSpawnTypes.RELIC_MEDIUM,
    'Titancall': WorldSpawnTypes.RELIC_MEDIUM,
    'Fort Barley': WorldSpawnTypes.RELIC_MEDIUM,
    "Captain's Dread": WorldSpawnTypes.RELIC_MEDIUM,
    'The Tusk': WorldSpawnTypes.RELIC_LARGE,
    # Great March
    'Violethome': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
    "Myrmidon's Stay": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
    'Remnant Villa': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
    'The Swan': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Leto': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Sitaria': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Dendró Field': WorldSpawnTypes.RELIC_MEDIUM,
	'Lionsfort': WorldSpawnTypes.RELIC_LARGE,
	'Camp Senti': WorldSpawnTypes.RELIC_LARGE,
    # Tempest Island
	'The Rush': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Plana Fada': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Surge Gate': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"Liar's Haven": WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Iris': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Gale': WorldSpawnTypes.RELIC_SMALL,
	'Reef': WorldSpawnTypes.RELIC_LARGE,
	'Blackwatch': WorldSpawnTypes.RELIC_LARGE,
	'Isle of Psyche': WorldSpawnTypes.RELIC_SMALL,
    # Marban Hollow
	'Lockheed': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Mox': WorldSpawnTypes.RELIC_SMALL,
	'The Spitrocks': WorldSpawnTypes.RELIC_SMALL,
	'Checkpoint Bua': WorldSpawnTypes.RELIC_SMALL,
	'Sanctum': WorldSpawnTypes.RELIC_MEDIUM,
	'Oster Wall': WorldSpawnTypes.RELIC_LARGE,
	"Maiden's Veil": WorldSpawnTypes.TOWN_BASE_SCHOOL,
    # Viper Pit
	'Blackthroat': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Moltworth': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Earl Crowley': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	"Serenity's Blight": WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Kirknell': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Fleck Crossing': WorldSpawnTypes.RELIC_SMALL,
	'Fort Viper': WorldSpawnTypes.RELIC_SMALL,
	'The Friars': WorldSpawnTypes.RELIC_LARGE,
    # Basin Sionnach
	'The Den': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Sess': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Cuttail Station': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Lamplight': WorldSpawnTypes.RELIC_SMALL,
	'Stoic': WorldSpawnTypes.RELIC_MEDIUM,
	'Basinhome': WorldSpawnTypes.RELIC_LARGE,
    # Stema Landing
	'The Spearhead': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Alchimio Estate': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Base Ferveret': WorldSpawnTypes.RELIC_SMALL,
	'Acies Overlook': WorldSpawnTypes.RELIC_SMALL,
	'The Wane': WorldSpawnTypes.RELIC_SMALL,
	'The Flair': WorldSpawnTypes.RELIC_SMALL,
	'Verge Wing': WorldSpawnTypes.RELIC_SMALL,
	'Base Sagitta': WorldSpawnTypes.RELIC_MEDIUM,
	'Ustio': WorldSpawnTypes.RELIC_LARGE,
    # DeadLands
	'The Salt Farms': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	"Callahan's Boot": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Spine': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Brine Glen': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Liberation Point': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"Callahan's Gate": WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"Sun's Hollow": WorldSpawnTypes.RELIC_MEDIUM,
	'The Pits': WorldSpawnTypes.RELIC_MEDIUM,
	'The Salt March': WorldSpawnTypes.RELIC_MEDIUM,
	"Iron's End": WorldSpawnTypes.RELIC_LARGE,
	'Abandoned Ward': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
    # The Heartlands
	'Greenfield Orchard': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Oleander Homestead': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Deeplaw Post': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Proexí': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Breach': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Blemish': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Barrony Ranch': WorldSpawnTypes.RELIC_SMALL,
	'The Plough': WorldSpawnTypes.RELIC_MEDIUM,
	'Barronswall': WorldSpawnTypes.RELIC_MEDIUM,
	'Fort Providence': WorldSpawnTypes.RELIC_LARGE,
    # Endless Shore
	'Iron Junction': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Tuatha Watchpost': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Wellchurch': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Brackish Point': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Woodbind': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Enduring Wake': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Saltbrook Channel': WorldSpawnTypes.TOWN_BASE_CENTER,
	'The Old Jack Tar': WorldSpawnTypes.RELIC_SMALL,
	'The Overland': WorldSpawnTypes.RELIC_MEDIUM,
	'Sídhe Fall': WorldSpawnTypes.RELIC_LARGE,
    # Westgate
	'Kingstone': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	"Lord's Mouth": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Gallows': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Longstone': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Westgate Keep': WorldSpawnTypes.RELIC_SMALL,
	'Holdfast': WorldSpawnTypes.RELIC_SMALL,
	'Lost Partition': WorldSpawnTypes.RELIC_MEDIUM,
	"Rancher's Fast": WorldSpawnTypes.RELIC_MEDIUM,
	'Wyattwick': WorldSpawnTypes.RELIC_MEDIUM,
	"Zeus' Demise": WorldSpawnTypes.RELIC_LARGE,
    # The Oarbreaker Isles
	'The Conclave': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Integrum': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Gold': WorldSpawnTypes.RELIC_LARGE,
	'Posterus': WorldSpawnTypes.RELIC_SMALL,
	'Silver': WorldSpawnTypes.RELIC_MEDIUM,
	'Fort Fogwood': WorldSpawnTypes.RELIC_MEDIUM,
	'Partisan Island': WorldSpawnTypes.RELIC_LARGE,
	'The Dirk': WorldSpawnTypes.RELIC_LARGE,
	'Grisly Refuge': WorldSpawnTypes.RELIC_LARGE,
    # Acrithia
	'Legion Ranch': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Thetus Ring': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Patridia': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Heir Apparent': WorldSpawnTypes.RELIC_SMALL,
	'The Brinehold': WorldSpawnTypes.RELIC_SMALL,
	'Swordfort': WorldSpawnTypes.RELIC_MEDIUM,
	'Nereid Keep': WorldSpawnTypes.RELIC_MEDIUM,
	'Camp Omicron': WorldSpawnTypes.RELIC_LARGE,
    # The Moors
	'The Cut': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Headstone': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	"Luch's Workshop": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'MacConmara Barrows': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	"Morrighan's Grave": WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Ogmaran': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Borderlane': WorldSpawnTypes.RELIC_SMALL,
	'The Spade': WorldSpawnTypes.RELIC_MEDIUM,
	'Wiccwalk': WorldSpawnTypes.RELIC_MEDIUM,
	"Gravekeeper's Holdfast": WorldSpawnTypes.RELIC_LARGE,
	'The Wind Hills': WorldSpawnTypes.RELIC_LARGE,
	'Reaching River': WorldSpawnTypes.RELIC_LARGE,
    # Weathered Expanse
	"Crow's Nest": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Wightwalk': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Weathering Halls': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Spirit Watch': WorldSpawnTypes.RELIC_SMALL,
	'Huntsfort': WorldSpawnTypes.RELIC_SMALL,
	'Necropolis': WorldSpawnTypes.RELIC_MEDIUM,
	'Frostmarch': WorldSpawnTypes.RELIC_MEDIUM,
	'Shattered Advance': WorldSpawnTypes.RELIC_LARGE,
	'Foxcatcher': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
    # Reaver's Pass
	'Scuttletown': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Keelhaul': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Breakwater': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Clay Coffer': WorldSpawnTypes.RELIC_SMALL,
	'The Bilge': WorldSpawnTypes.RELIC_SMALL,
	'Thimble Base': WorldSpawnTypes.RELIC_SMALL,
	'Fort Rictus': WorldSpawnTypes.RELIC_LARGE,
    # Loch Mor
	"Mercy's Wish": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Feirmor': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"Moon's Copse": WorldSpawnTypes.RELIC_SMALL,
	'The Roilfort': WorldSpawnTypes.RELIC_SMALL,
	'Tomb of the First': WorldSpawnTypes.RELIC_MEDIUM,
	'Westmarch': WorldSpawnTypes.RELIC_MEDIUM,
	'Market Road': WorldSpawnTypes.RELIC_LARGE,
    # Morgen's Crossing
	'Lividus': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Quietus': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Allsight': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Eversus': WorldSpawnTypes.RELIC_SMALL,
	"Bastard's Block": WorldSpawnTypes.RELIC_MEDIUM,
	"Callum's Descent": WorldSpawnTypes.RELIC_LARGE,
    # Stonecradle
	'Fading Lights': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"The Heir's Knife": WorldSpawnTypes.RELIC_SMALL,
	"World's End": WorldSpawnTypes.RELIC_SMALL,
	'The Cord': WorldSpawnTypes.RELIC_SMALL,
	'Trammel Pool': WorldSpawnTypes.RELIC_MEDIUM,
	'The Long Fast': WorldSpawnTypes.RELIC_MEDIUM,
	'The Dais': WorldSpawnTypes.RELIC_MEDIUM,
	'The Reach': WorldSpawnTypes.RELIC_LARGE,
	'Buckler Sound': WorldSpawnTypes.TOWN_BASE_CENTER,
    # Allod's Bight
	'Scurvyshire': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"Mercy's Wail": WorldSpawnTypes.TOWN_BASE_CENTER,
	'The Stone Plank': WorldSpawnTypes.RELIC_SMALL,
	'Homesick': WorldSpawnTypes.RELIC_SMALL,
	'Rumhold': WorldSpawnTypes.RELIC_SMALL,
	'Belaying Trace': WorldSpawnTypes.RELIC_MEDIUM,
	'The Turncoat': WorldSpawnTypes.RELIC_LARGE,
    # Kalokai
	'Sweethearth': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Hallow': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Baccae Ridge': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Camp Tau': WorldSpawnTypes.RELIC_SMALL,
	'Lost Greensward': WorldSpawnTypes.RELIC_MEDIUM,
	'Sourtooth': WorldSpawnTypes.RELIC_MEDIUM,
	"Night's Regret": WorldSpawnTypes.RELIC_LARGE,
    # Red River
	'Minos': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Judicium': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Penance': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Cannonsmoke': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Fort Matchwood': WorldSpawnTypes.RELIC_SMALL,
	'Climb': WorldSpawnTypes.RELIC_MEDIUM,
	'Camp Upsilon': WorldSpawnTypes.RELIC_MEDIUM,
	'Victoria Hill': WorldSpawnTypes.RELIC_LARGE,
    # Origin
	'Finis': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Initium': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Teichotima': WorldSpawnTypes.TOWN_BASE_CENTER,
	'World Star': WorldSpawnTypes.RELIC_SMALL,
	'Arise': WorldSpawnTypes.RELIC_MEDIUM,
	'The Steel Road': WorldSpawnTypes.RELIC_MEDIUM,
	'Dormio': WorldSpawnTypes.RELIC_LARGE,
    # Howl County
	'Little Lamb': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Teller Farm': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Hungry Wolf': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Great Warden Dam': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Fort Red': WorldSpawnTypes.RELIC_SMALL,
	'Fort Rider': WorldSpawnTypes.RELIC_MEDIUM,
	'Slipgate Outpost': WorldSpawnTypes.RELIC_LARGE,
	'Sickleshire': WorldSpawnTypes.RELIC_LARGE,
    # The Clahstra
	'East Narthex': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Watchful Nave': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Transept': WorldSpawnTypes.RELIC_SMALL,
	'Bewailing Fort': WorldSpawnTypes.RELIC_MEDIUM,
	'The Vault': WorldSpawnTypes.RELIC_MEDIUM,
	'Weephome': WorldSpawnTypes.RELIC_LARGE,
	'The Treasury': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Third Chapter': WorldSpawnTypes.TOWN_BASE_SCHOOL,
    # Schackled Chasm
	'The Vanguard': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Grave of Erastos': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Savages': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Reflection': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Silk Farms': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Gorgon Grove': WorldSpawnTypes.RELIC_SMALL,
	'Limewood Holdfast': WorldSpawnTypes.RELIC_SMALL,
	'Firstmarch': WorldSpawnTypes.RELIC_SMALL,
	'The Bell Toll': WorldSpawnTypes.RELIC_LARGE,
	"Simo's Run": WorldSpawnTypes.RELIC_LARGE,
    # Speaking Woods
	'Sotto Bank': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Tine': WorldSpawnTypes.TOWN_BASE_CENTER,
	'The Filament': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Hush': WorldSpawnTypes.RELIC_SMALL,
	'Inari Base': WorldSpawnTypes.RELIC_MEDIUM,
	'Fort Blather': WorldSpawnTypes.RELIC_MEDIUM,
	'Stem': WorldSpawnTypes.RELIC_MEDIUM,
	'Wound': WorldSpawnTypes.RELIC_LARGE,
    # Terminus
	"Warlord's Stead": WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Therizó': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Winding Bolas': WorldSpawnTypes.RELIC_SMALL,
	'Thunderbolt': WorldSpawnTypes.RELIC_MEDIUM,
	'Bloody Palm Fort': WorldSpawnTypes.RELIC_LARGE,
	'Cerberus Wake': WorldSpawnTypes.RELIC_LARGE,
    # The Linn of Mercy
	'Outwich Ranch': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Prairie Bazaar': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Long Whine': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Crimson Gardens': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Rotdust': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The First Coin': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Last Grove': WorldSpawnTypes.RELIC_SMALL,
	'Lathair': WorldSpawnTypes.RELIC_SMALL,
	'Fort Duncan': WorldSpawnTypes.RELIC_MEDIUM,
	'Hardline': WorldSpawnTypes.RELIC_LARGE,
	'Ulster Falls': WorldSpawnTypes.TOWN_BASE_SCHOOL,
    # Clanshead Valley
	'The Pike': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The King': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Sweetholt': WorldSpawnTypes.RELIC_SMALL,
	'Fallen Crown': WorldSpawnTypes.RELIC_SMALL,
	'Fort Esterwild': WorldSpawnTypes.RELIC_MEDIUM,
	'Fort Windham': WorldSpawnTypes.RELIC_MEDIUM,
	'Fort Ealar': WorldSpawnTypes.RELIC_LARGE,
    # Godcrofts
	'The Axehead': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Isawa': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Fleecewatch': WorldSpawnTypes.RELIC_SMALL,
	'Argosa': WorldSpawnTypes.RELIC_SMALL,
	'Saegio': WorldSpawnTypes.RELIC_MEDIUM,
	'Exile': WorldSpawnTypes.RELIC_MEDIUM,
	'Protos': WorldSpawnTypes.RELIC_LARGE,
	'Lipsia': WorldSpawnTypes.RELIC_LARGE,
	'Ursa Base': WorldSpawnTypes.RELIC_LARGE,
    # Nevish Line
	'Blackcoat Way': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Mistle Shrine': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Scrying Belt': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Blinding Stones': WorldSpawnTypes.RELIC_SMALL,
	'Grief Mother': WorldSpawnTypes.RELIC_SMALL,
	'Unruly': WorldSpawnTypes.RELIC_MEDIUM,
	'Princefal': WorldSpawnTypes.RELIC_LARGE,
	'Tomb Father': WorldSpawnTypes.RELIC_MEDIUM,
    # Callum's Cape
	'Holdout': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"Callum's Keep": WorldSpawnTypes.TOWN_BASE_CENTER,
	'Lookout': WorldSpawnTypes.RELIC_SMALL,
	'Naofa': WorldSpawnTypes.RELIC_SMALL,
	'Ire': WorldSpawnTypes.RELIC_SMALL,
	'Camp Hollow': WorldSpawnTypes.RELIC_MEDIUM,
	'Scouts Jest': WorldSpawnTypes.RELIC_LARGE,
    # Fisherman's Row
	'Black Well': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Eidolo': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Arcadia': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"Hangman's Court": WorldSpawnTypes.RELIC_SMALL,
	'Fort Ember': WorldSpawnTypes.RELIC_MEDIUM,
	'Dankana Post': WorldSpawnTypes.RELIC_MEDIUM,
	'Peripti Landing': WorldSpawnTypes.RELIC_MEDIUM,
	'Oceanwatch': WorldSpawnTypes.RELIC_LARGE,
	'The Satyr Stone': WorldSpawnTypes.RELIC_LARGE,
    # Umbral Wildwood
	'Thunderfoot': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Amethyst': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Stray': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Sentry': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Foundry': WorldSpawnTypes.RELIC_MEDIUM,
	"Hermit's Rest": WorldSpawnTypes.TOWN_BASE_SCHOOL,
	"Clotho's Refuge": WorldSpawnTypes.RELIC_SMALL,
	"Atropos' Fate": WorldSpawnTypes.RELIC_SMALL,
	'Vagrant Bastion': WorldSpawnTypes.RELIC_MEDIUM,
	'Goldenroot Ranch': WorldSpawnTypes.RELIC_LARGE,
	"Lachesis' Tally ": WorldSpawnTypes.RELIC_LARGE,
    # Reaching Trail
	'Nightchurch': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Elksford': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Reprieve': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Mousetrap': WorldSpawnTypes.RELIC_LARGE,
	'Dwyerstown': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Ice Ranch': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Brodytown': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Harpy': WorldSpawnTypes.RELIC_SMALL,
	'Fort Mac Conaill': WorldSpawnTypes.RELIC_MEDIUM,
	'The Ark': WorldSpawnTypes.RELIC_LARGE,
	'Limestone Holdfast': WorldSpawnTypes.RELIC_LARGE,
    # Stlican Shelf
	'The Pale House': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Breaker Town': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Port of Rime': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Thornhold': WorldSpawnTypes.RELIC_SMALL,
	'Briar': WorldSpawnTypes.RELIC_MEDIUM,
	'The Old Mourn': WorldSpawnTypes.RELIC_MEDIUM,
	'Fort Hoarfrost': WorldSpawnTypes.RELIC_LARGE,
	'The South Wind': WorldSpawnTypes.RELIC_LARGE,
	'Vulpine Watch': WorldSpawnTypes.TOWN_BASE_SCHOOL,
    # Callahan's Passage
	'Cragstown': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'White Chapel': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Solas Gorge': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Overlook Hill': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Crumbling Post': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Latch': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Crumbling Passage': WorldSpawnTypes.RELIC_SMALL,
	'Scáth Passing': WorldSpawnTypes.RELIC_MEDIUM,
	'The Procession': WorldSpawnTypes.RELIC_LARGE,
	'Lochan Berth': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
    # Ash Fields
	'Ashtown': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Electi': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Cometa': WorldSpawnTypes.RELIC_SMALL,
	'The Ashfort': WorldSpawnTypes.RELIC_SMALL,
	'The Calamity': WorldSpawnTypes.RELIC_MEDIUM,
	'Sootflow': WorldSpawnTypes.RELIC_LARGE,
	'Camp Omega': WorldSpawnTypes.RELIC_LARGE,
    # King's Cage
	'Gibbet Fields': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Southblade': WorldSpawnTypes.RELIC_SMALL,
	'Slipchain': WorldSpawnTypes.RELIC_SMALL,
	'Scarlethold': WorldSpawnTypes.RELIC_MEDIUM,
	'Den of Knaves': WorldSpawnTypes.RELIC_MEDIUM,
	'Eastknife': WorldSpawnTypes.RELIC_LARGE,
	'The Bailie': WorldSpawnTypes.RELIC_MEDIUM,
	'The Manacle': WorldSpawnTypes.TOWN_BASE_CENTER,
    # The Drowned Vale
	'Vessel': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Bootnap': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'The Saltcaps': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Coaldrifter Stead': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Loggerhead': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'The Baths': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Singing Serpents': WorldSpawnTypes.RELIC_SMALL,
	'Eastmarch': WorldSpawnTypes.RELIC_MEDIUM,
	"Wisp's Warning": WorldSpawnTypes.RELIC_MEDIUM,
	'The Wash': WorldSpawnTypes.RELIC_MEDIUM,
	'Splinter Pens': WorldSpawnTypes.RELIC_LARGE,
    # Farranac Coast
	'The Bone Haft': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	"Macha's Keening": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Huskhollow': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Victa': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Mara': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Scarp of Ambrose': WorldSpawnTypes.RELIC_SMALL,
	'Transient Valley': WorldSpawnTypes.RELIC_SMALL,
	'Scythe': WorldSpawnTypes.RELIC_MEDIUM,
	'Pleading Wharf': WorldSpawnTypes.RELIC_LARGE,
	'Terra': WorldSpawnTypes.RELIC_MEDIUM,
	'The Jade Cove': WorldSpawnTypes.TOWN_BASE_CENTER,
    # Sableport
	"Light's End": WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Cinderwick': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Barronhome': WorldSpawnTypes.TOWN_BASE_CENTER,
	"The Robin's Nest": WorldSpawnTypes.RELIC_SMALL,
	'The Pendant': WorldSpawnTypes.RELIC_MEDIUM,
	'Talonsfort': WorldSpawnTypes.RELIC_MEDIUM,
	'The Whetstone': WorldSpawnTypes.RELIC_LARGE,
	# Palantine Berm
	'Windburn Landing': WorldSpawnTypes.RELIC_LARGE,
	'The Pippeli Stones': WorldSpawnTypes.RELIC_MEDIUM,
	'The Droll': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Leiri Hermanni': WorldSpawnTypes.RELIC_MEDIUM,
	'Vendett': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Dryfeld': WorldSpawnTypes.RELIC_MEDIUM,
	'Underlook': WorldSpawnTypes.RELIC_SMALL,
	# Olavi's Wake
	'Kulkue': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Yöohja': WorldSpawnTypes.RELIC_MEDIUM,
	'Koskinla': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Ilmari Bridge': WorldSpawnTypes.RELIC_LARGE,
	# Pari Peak
	'Itään': WorldSpawnTypes.RELIC_SMALL,
	'Camp Surista': WorldSpawnTypes.RELIC_LARGE,
	'Pariah': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Little Raakkua': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Kohina Base': WorldSpawnTypes.RELIC_SMALL,
	# Kuura Strand
	'Martti': WorldSpawnTypes.TOWN_BASE_CENTER,
	'Lumia': WorldSpawnTypes.RELIC_MEDIUM,
	'Menneen': WorldSpawnTypes.RELIC_SMALL,
	'Suosalo': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	'Faden Point': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Talven': WorldSpawnTypes.RELIC_SMALL,
	# The Gutter
	'Suojus': WorldSpawnTypes.RELIC_LARGE,
	'Rotko Camp': WorldSpawnTypes.RELIC_LARGE,
	'Rikki Sarana': WorldSpawnTypes.RELIC_SMALL,
	'Salaoja Road': WorldSpawnTypes.RELIC_MEDIUM,
	'Kuoppa': WorldSpawnTypes.TOWN_BASE_SCHOOL,
	'Lost Kaivo': WorldSpawnTypes.RELIC_MEDIUM,
	'The Parras': WorldSpawnTypes.TOWN_BASE_POST_OFFICE,
	# Lykos Isle
	'Erebus Islet': WorldSpawnTypes.,
	'Astutia': WorldSpawnTypes.,
	'Fort Guile': WorldSpawnTypes.,
	'The Squall': WorldSpawnTypes.,
	'Cyrus': WorldSpawnTypes.,
	'Mārudia': WorldSpawnTypes.,
	'Aetherwood': WorldSpawnTypes.,
	# Wresta
	'Latro Manor': WorldSpawnTypes.,
	'Ratchet': WorldSpawnTypes.,
	'Adripio': WorldSpawnTypes.,
	'Garion Slip': WorldSpawnTypes.,
	'Argan Isle': WorldSpawnTypes.,
	'Scallyhold': WorldSpawnTypes.,
	"Toad's Plinth": WorldSpawnTypes.,
	# Onyx
	'Garland': WorldSpawnTypes.,
	"Beholder's Span": WorldSpawnTypes.,
	'The Waif': WorldSpawnTypes.,
	'Dexam': WorldSpawnTypes.,
	'The Brink': WorldSpawnTypes.,
	'Cisterna Run': WorldSpawnTypes.,
	# Tyrant Foothills
	'Bandolier Base': WorldSpawnTypes.,
	'Azmar': WorldSpawnTypes.,
	'Scrapegrace': WorldSpawnTypes.,
	'Onioncap': WorldSpawnTypes.,
	'Lugria': WorldSpawnTypes.,
	"Duelist's Scarp": WorldSpawnTypes.,
	'Northern Sky Hold': WorldSpawnTypes.,
	# Piper's Enclave
	'Maenalius Cove': WorldSpawnTypes.,
	'Syrinx Pass': WorldSpawnTypes.,
	'Aegocerus Fortress': WorldSpawnTypes.,
	"Pan's Villa": WorldSpawnTypes.,
	'Reedhurst': WorldSpawnTypes.,
	'House of Lyterius': WorldSpawnTypes.,
}


CODENAME_TO_GAMENAME = {
    # Materials
    'Cloth': 'Basic Materials',
    'Wood': 'Refined Materials',
    'FacilityMaterials1': 'Construction Materials',
    'FacilityMaterials2': 'Processed Construction Materials',
    'FacilityMaterials3': 'Steel Construction Materials',
    'FacilityMaterials4': 'Assembly Materials I',
    'FacilityMaterials5': 'Assembly Materials II',
    'FacilityMaterials6': 'Assembly Materials III',
    'FacilityMaterials7': 'Assembly Materials IV',
    'FacilityMaterials8': 'Assembly Materials V',
    'FacilityMaterials9': 'Rare Alloys',
    'FacilityMaterials10': 'Unstable Substances',
    'FacilityMaterials11': 'Thermal Shielding',
    'ShipPart1': 'Naval Hull Segments',
    'ShipPart2': 'Naval Shell Plating',
    # Structures
    'FacilityVehicleFactory1': 'Small Assembly Station',
    'FacilityVehicleFactory2': 'Large Assembly Station',
    'FacilityVehicleFactory3': 'Dry Dock',
    'LargeShipBaseShip': 'Longhook',
    'VehicleFactory': 'Garage',
}
