REGIONS = {
    'Acrithia': ['Patridia', 'Nereid Kepp', 'The Brimehold', 'Legion Ranch', 'Camp Omicron', 'Heir Apparent', 'Thetus Ring', 'Swordfort'],
    "Allod's Bight": ['The Stone Plank', "Mercy's Wail", 'The Turncoat', 'Belaying Trace', 'Homesick', 'Rumhold', 'Scurvyshire'],
    'Ash Fields': ['Cometa', 'The Calamity', 'Ashtown', 'Sootflow', 'The Ashfort', 'Camp Omega', 'Electi'],
    'Basin Sionnach': ['Cuttail Station', 'Stoic', 'Lamplight', 'The Den', 'Bassinhome', 'Sess'],
    "Callahan's Passage": ['Cragstown', 'White Chapel', 'The Procession', 'The Latch', 'Overlook Hill', 'Crumbling Passage', 'Crumbling Post', 'Scáth Passing', 'Lochan Berth', 'Solas Gorge'],
    "Callum's Cape": ['Naofa', 'Scouts Jest', 'Ire', 'Lookout', 'Holdout', 'Camp Hollow', "Callum's Keep"],
    'Clanshead Valley': ['Fallen Crown', 'Fort Windham', 'The King', 'Sweetholt', 'Fort Esterwild', 'The Pike', 'Fort Ealar'],
    'Deadlands': ['The Salt Farms', 'Brine Glen', 'The Salt March', "Callahan's Gate", "Callahan's Boot", "Iron's End", 'The Spine', 'Liberation Point', "Sun's Hollow", 'The Pits', 'Abandoned Ward'],
    'Endless Shore': ['Iron Junction', 'The Overland', 'Woodbind', 'Tuatha Watchpost', 'Evil Eye', 'Dannan Ridge', 'Vulpine Watch', 'Wellchurch', 'Brackish Point', 'Saltbrook Channel', 'Enduring Wake', 'The Old Jack Tar'],
    'Farranac Coast': ['Victa', 'Pleading Wharf', "Macha's Keening", 'Mara', 'Scythe', 'The Jade Cove', 'Scarp of Ambrose', 'Luxta Homestead', 'The Bone Haft', 'The Spearhead', 'Terra'],
    "Fisherman's Row": ['Arcadia', 'Fort Ember', 'The Satyr Stone', "Hangmen's Court", 'The Tree Sisters', 'Eidolo', 'Peripti Landing', 'Black Well', 'Oceanwatch', 'Partisan Island'],
    'Godcrofts': ['Anchor Beach', 'Blackwatch', 'Protos', 'The Axehead', 'Skodio', 'Promithiens', 'Isawa', 'The FLeece Road'],
    'Great March': ['Violethome', 'Leto', 'Camo Senti', "Myrmidon's Stay", 'Remnant Villa', 'Lionsfort', 'Dendro Field', "Sitaria", 'The Swan'],
    'Howl County': ['Hungry Wolf', 'Slipgate Outpost', 'Great Warden Dam', 'Fort Red', 'Sickelshire', 'Little Lamb', 'Teller Farm', 'Fort Rider'],
    'Kalokai': ["Night's Regret", 'Sourtooth', 'Sweetearth', 'Camp Tau', 'Hallow', 'Baccae Ridge', 'Lost Greensward'],
    'Loch Mór': ['Market Road', 'Tomb of the First', "Mercy's Wish", 'Westmarch', "Moon's Copse", 'The Roilfort', 'Feirmor'],
    'Marban Hollow': ['Lockheed', 'Oster Wall', 'Mox', 'Checkpoint Bua', "Maiden's Veil", 'The Spitrocks', 'Sanctum'],
    "Morgen's Crossing": ['Eversus', 'Allsight', "Bastard's Block", 'Quietus', 'Lividus', 'Warmonger Bay'],
    'Nevish Line': ['Blinding Stones', 'The Scrying Belt', 'Unruly', 'Mistle Shrine', 'Grief Mother', 'Princefal', 'Blackcoat Way', 'Tomb Father'],
    'Origin': ['Finis', 'Arise', 'Initium', 'Dormio', 'World Star', 'Teichotima'],
    'Reaching Trail': ['Limestone Holdfast', 'Dwyerstown', 'Brodytown', 'Elksford', 'Ice Ranch', 'Nightchurch', 'Harpy', 'Reprieve', "Fort Mac Conaill's", 'The Ark', 'Mousetrap'],
    'Red River': ['Camp Upsilon', 'Penance', 'Fort Matchwood', 'Climb', 'Judicium', 'Victoria Hill', 'Cannonsmoke', 'Minos'],
    'Schackeld Chasm': ['Savages', 'The Grave of Rastus', 'The Beli Toll', 'Firstmarch', 'The Vanguard', 'Limewood Holdfast', 'Gorgon Grove', 'Reflection', 'Silk Farm', "Simo's Run"],
    'Speaking Woods': ['Hush', 'Inari Base', 'Tine', 'Sotto Bank', 'Fort Blather', 'Stem', 'The Filament', 'Wound'],
    'Stonecradle': ['The Dais', 'The Reach', 'Trammel Pool', 'Fading Lights', 'The Cord', 'Buckler Sound', "World's End", "The Heir's Knife", 'The Long Fast'],
    'Tempest Island': ['Isle of Psyche', 'The Gale', "Liar's Heaven", 'The Iris', 'Surge Gate', 'The Rush', 'Reef', 'Lost Airchal', 'Alchimio Estate'],
    'Terminus': ['Therizó', 'Bloody Palm', 'Winding Bolas', 'Thunderbolt', "Warlord's Stead", 'Cerberus Wake'],
    'The Drowned Vale': ['Loggerhead', "Wisp's Warning", 'The Wash', 'Eastmarch', 'Vessel', 'Splinter Pens', 'The Baths', 'Coaldrifter Stead', 'Bootnap', 'Singing Serpents', 'The Saltcaps'],
    'The Fingers': ['Titancall', 'The Old Captain', 'Fort Barley', 'Second Man', 'The Routed', 'The Tusk', "Headsman's Villa", 'Plankhouse'],
    'The Heartlands': ['Deeplaw Post', 'The Breach', 'Barrony Ranch', 'The Plough', 'Greenfield Orchard', 'Fort Providence', 'The Blemish', 'Barronswall', 'Oleander Homestead', 'Proexí'],
    'The Linn of Mercy': ['The Long Whine', 'Rotdust', 'Lathair', 'Outwich Ranch', 'Fort Duncan', 'The Prairie Bazaar', 'The First Coin', 'The Last Grove', 'The Crimson Gardens', 'Hardline', 'Ulster Falls'],
    'The Moors': ['Reaching River', 'The Spade', 'Headstone', "Gravekeeper's Holdfast", 'The Cut', 'The Wind Hills', 'MacConmara Barrows', 'Wiccwalk', "Morrighan's Grave", "Luch's Workshop", 'Borderlane', 'Reaching River', 'Ogmaran'],
    'The Oarbreaker Isles': ['Gold', 'Reliqua', 'The Ides', 'Posterus', 'Skelter Course', 'The Conclave', "Lion's Head", 'Integrum', 'Base Akri'],
    'Umbral Wildwood': ['The Foundry', 'Golden Root Ranch', 'Thunderfoot', 'Sentry', "Atropos' Fate", "Hermit's Rest", "Lachesis' Tally", 'Amethyst', "Clotho's Refuge", 'Vagrant Bastion', 'Stray'],
    'Viper Pit': ["Serenity's Blight", 'Flech Crossing', 'Earl Crowley', 'Molworth', 'Blackthroat', 'The Friars', 'Fort Viêr', 'Fleck Crossing', 'Kirknell'],
    'Weathered Expanse': ['The Weathering Halls', 'Port of Rime', 'Wightwalk', 'Huntsfort', 'Shattered Advance', 'Frostmarch', "Crow's Nest", 'Necropolis', 'Foxcatcher'],
    'Westgate': ['Sanctuary', 'The Gallows', 'Holdfast', "Rancher's Fast", 'Kingstown', "Lord's Mouth", 'Lost Partition', 'Westgate Keep', 'Longstone', "Zeus' Demise", 'Wyattwick']
}