name: Run tests on wiki module commands

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Verify uv installation
        run: |
          echo "Checking uv version:"
          uv --version
      - name: Install project dependencies group
        run: |
          uv sync --all-groups
      - name: Tests with pytest
        run: |  
          pytest -v -s -n auto
