name: Run tests on wiki module commands

on:
  pull_request:
    types: [opened, synchronize]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Verify uv installation
        run: |
          echo "Installed uv version:"
          uv --version

      - name: Install project requirements & dependencies
        run: |
          uv sync --all-groups

      - name: Run synchronous tests
        run: |
          uv run pytest -v -s -n auto tests/test_wiki_module.py

      - name: Run asynchronous tests
        run: |  
          uv run pytest -v -s tests/test_async_wiki_module.py
